export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const SUBMIT_SEARCH_FAILURE = 'SUBMIT_SEARCH_FAILURE';
export const SET_LOADING_SEARCH_TRUE = 'SET_LOADING_SEARCH_TRUE';
export const SET_LOGIN = 'SET_LOGIN';
export const GET_VISUALIZED_COURSE = 'GET_VISUALIZED_COURSE';
export const GET_VISUALIZED_COURSE_FAILURE = 'GET_VISUALIZED_COURSE_FAILURE';
export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = 'UPDATE_USER';
