export const CHANGE_FILTERS = 'CHANGE_FILTERS';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const SUBMIT_SEARCH_FAILURE = 'SUBMIT_SEARCH_FAILURE';
export const SET_LOADING_SEARCH_TRUE = 'SET_LOADING_SEARCH_TRUE';
export const SET_LOGIN = 'SET_LOGIN';
export const SET_CENTERED_COURSE = 'SET_CENTERED_COURSE';
export const SET_CENTERED_COURSE_FAILURE = 'SET_CENTERED_COURSE_FAILURE';
export const UPDATE_VISUALIZED_COURSES = 'UPDATE_VISUALIZED_COURSES';
