# This is a Heroku deployment workflow

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ deploy ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: AkhileshNS/heroku-deploy@v3.3.6
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        # Email that you use with heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        # The appname to use for deploying/updating
        heroku_app_name: "course-flo"
        # The branch that you would like to deploy to Heroku
        branch: deploy # optional, default is HEAD
        # Contents of the Procfile to save and deploy
        procfile: "web: npm start" # optional, default is 
